---
id: imp
name: IMP
full: Webmail application
description: >-
  IMP, the Internet Mail Program, is one of the most popular and widely deployed
  open source webmail applications in the world. It allows universal, web-based
  access to IMAP and POP3 mail servers and provides Ajax, mobile and traditional
  interfaces with a rich range of features normally found only in desktop email
  clients.
list: ~
type: application
homepage: https://www.horde.org/apps/imp
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 7.0.0alpha2
  api: 7.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^7
    composer:
      horde/horde: ^5
      horde/auth: ^2
      horde/browser: ^2
      horde/cache: ^2
      horde/compress: ^2
      horde/core: ^2.17
      horde/crypt: ^2.7
      horde/crypt_blowfish: ^1
      horde/css_parser: ^1
      horde/date: ^2
      horde/editor: ^2.0.4
      horde/exception: ^2
      horde/icalendar: ^2.1
      horde/image: ^2.6
      horde/imap_Client: ^2.27
      horde/itip: ^2.1
      horde/listheaders: ^1.1
      horde/logintasks: ^2
      horde/mail: ^2.5
      horde/mail_autoconfig: ^1
      horde/mime: ^2.10
      horde/mime_viewer: ^2
      horde/nls: ^2
      horde/notification: ^2
      horde/pack: ^1
      horde/perms: ^2
      horde/spellchecker: ^2
      horde/stream: ^1.4
      horde/stream_filter: ^2
      horde/stream_wrapper: ^2.1
      horde/support: ^2.0.5
      horde/text_filter: ^2.1
      horde/text_flowed: ^2
      horde/tree: ^2
      horde/url: ^2.2
      horde/util: ^2.4
      horde/vfs: ^2
      horde/view: ^2
    ext:
      dom: '*'
      gettext: '*'
      hash: '*'
      json: '*'
  optional:
    composer:
      horde/history: ^2
      horde/http: ^2
      horde/mongo: ^1
      horde/service_gravatar: ^1
    pear:
      phpseclib.sourceforge.net/File_ASN1: '*'
    ext:
      openssl: '*'
